### ISSUE TITLE
Is it possible to save cad solid file from 3d poly lines ?

### ISSUE THREAD

**Issue by selvakarna** [rougier/python-opengl#34]
Is it possible to save cad solid file from 3d poly lines ?

**Comment by rougier** [comment]
I'm not sure I understand your question. What do you call cad solid file ?

**Comment by selvakarna** [comment]
Hi @rougier , Solid means 3d surface or polylines are save as STEP or IGES, this file are support only CAD Software.

**Comment by rougier** [comment]
Thanks for the precision. I cannot answer your question because I'm not familiar with STEP or IGES file format.
