### ISSUE TITLE
from glumpy.ext import freetype - RuntimeError('Freetype library not found')

### ISSUE THREAD

**Issue by jeff5048** [rougier/python-opengl#4]
Hi,
I am new to Python programming.  I am trying to work through this online book:
http://www.labri.fr/perso/nrougier/python-opengl/
I have installed the libraries it recommends.  
Python 3.6.0
Numpy 1.12.0
Scipy 0.18.1
Cython 0.25.2
Triangle 20170106
Glumpy 1.0.6

My Versions:
Python 3.6.5
numpy (1.14.5)
scipy (1.1.0)
Cython (0.28.3)
triangle (20170429)
glumpy (1.0.6)

I am getting a lot of errors from the glumpy library.  It started with freeType.  An example error:

File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\glumpy\ext\freetype\__init__.py", line 49, in <module>
    raise RuntimeError('Freetype library not found')
RuntimeError: Freetype library not found

The code was breaking on the line:
from glumpy.ext import freetype

This error is occurring for all imported libraries loading by way of:
from glumpy.ext import LIBRARY 

The libraries appear to be in the “glumpy/ext” folder but Python is not finding them.

I’m stuck and can’t get beyond this.  Any help would be appreciated.

Windows 10 Pro
64 bit OS and processor
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32

Thanks,
Jeff

Code:

# -----------------------------------------------------------------------------
# Python & OpenGL for Scientific Visualization
# www.labri.fr/perso/nrougier/python+opengl
# Copyright (c) 2017, Nicolas P. Rougier
# Distributed under the 2-Clause BSD License.
# -----------------------------------------------------------------------------
from glumpy import app, gloo, gl

vertex = """
    attribute vec2 position;
    void main(){ gl_Position = vec4(position, 0.0, 1.0); } """

fragment = """
    void main() { gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0); } """

# Create a window with a valid GL context
window = app.Window()

# Build the program and corresponding buffers (with 4 vertices)
quad = gloo.Program(vertex, fragment, count=4)

# Upload data into GPU
quad['position'] = (-1,+1), (+1,+1), (-1,-1), (+1,-1)

# Tell glumpy what needs to be done at each redraw
@window.event
def on_draw(dt):
    window.clear()
    quad.draw(gl.GL_TRIANGLE_STRIP)

# Run the app
app.run()

**Comment by jeff5048** [comment]
Update:  I found that by placing a period before the "gumpy." in the code "from glumpy.XXXX import" to make it look like "from .glumpy.XXXX import" resolved much of the issues.  The use of which seemed inconsistent because some code errored-out with the period.  This has something to do with revative vs. absolute file references.  But there are other issues, too late in the day to get into now.

**Comment by jeff5048** [comment]
I think the above issue has been resolved by the ".glumpy.XXXX import" method as now I am getting openGL errors.

**Comment by rougier** [comment]
You're right, it might be a relative / absolute path problem but I'm not sure of the exact reason though.
By the way, when you post code, you have to surround by triple backquotes such that it is displayed nicely on GitHub (I modified your post to add the triple backquotes).

**Comment by Utkarsh22Ahuja** [comment]
Hey rougier 
I am also receiving same error. Please help. I followed everything you've written over its official documentation website. Please help. 
https://glumpy.readthedocs.io/en/latest/

Another doubt, I don't understand what is python3 folder? Where am I supposed to copy those dlls? And the statement either of the dlls, I am implying for win64 since my system is on win64. 
The guidance you gave is still a dilemma for a newbie like me. I don't have a lot of experience in this thing. Please help rougier. Please....

**Comment by Utkarsh22Ahuja** [comment]
Guys please respond.

**Comment by rougier** [comment]
I've answered you in the issue you opened.
