### ISSUE TITLE
flickering outline around line segments in agg-segments.py

### ISSUE THREAD

**Issue by bluebarnacles** [rougier/python-opengl#50]
When I run code/chapter-09/agg-segments.py, I get a flickering outline around every line segment.

Python: 3.7.8 (amd64)
glumpy: 1.1.0 (amd64 wheel downloaded from https://www.lfd.uci.edu/~gohlke/pythonlibs/#glumpy)
PyOpenGL: 3.1.5 (amd64 wheel downloaded from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl)
numpy: 1.19.0
OS: Windows 10
GPU: NVIDIA GeForce GTX 1060
Screen Resolution: 3240 x 2160

Screen capture:
![image](https://user-images.githubusercontent.com/5144579/87127786-60273100-c243-11ea-9107-a3cfe76bf940.png)

**Comment by rougier** [comment]
That's weird. I never saw that. Antialias seems correct but it has if there was a background noise behind. Can you try to change the color of the line to check if the noise comes from the line?

**Comment by bluebarnacles** [comment]
OK I changed the color of the line to (0.0, 0.7, 0.0). Still seeing the flickery outline, in antialias color black:
![image](https://user-images.githubusercontent.com/5144579/87219344-0724cf00-c30f-11ea-99b2-ad43fc38f51b.png)

**Comment by bluebarnacles** [comment]
Completing the if statement solves it for me:

diff --git a/code/chapter-09/agg-segments.py b/code/chapter-09/agg-segments.py
index b869a5e..732f7c0 100644
--- a/code/chapter-09/agg-segments.py
+++ b/code/chapter-09/agg-segments.py
@@ -61,8 +61,8 @@ fragment = """
       else
           d = abs(v_p.y) - v_thickness/2.0 + antialias/2.0;
       if( d < 0)
-          gl_FragColor = vec4(0.0, 0.0, 0.0, v_alpha);
-      else if (d < antialias) {
+          gl_FragColor = vec4(0.0, 0.7, 0.0, v_alpha);
+      else {
           d = exp(-d*d);
           gl_FragColor = vec4(0.0, 0.0, 0.0, d*v_alpha);
       }

![image](https://user-images.githubusercontent.com/5144579/87219539-f5442b80-c310-11ea-8a29-3c7c24d12560.png)

**Comment by rougier** [comment]
Weird. But I'm happy it's working. Do you have gl.clear statement somwhere in your python code ? That could explain the garbage and the fix you found.

**Comment by bluebarnacles** [comment]
This file uses glumpy.app.Window.clear(), so it does seem to use gl.clear.

This is a bug in rougier/python-opengl/code/chapter-09/agg-segments.py, triggered by not setting the fragment color for all cases in that shader. If I change the fragment shader to always set gl_FragColor, it solves the problem:

![image](https://user-images.githubusercontent.com/5144579/87261641-dad29500-c46b-11ea-8ffd-21f37861b7a0.png)


diff --git a/code/chapter-09/agg-segments.py b/code/chapter-09/agg-segments.py
index b869a5e..60054b0 100644
--- a/code/chapter-09/agg-segments.py
+++ b/code/chapter-09/agg-segments.py
@@ -51,21 +51,24 @@ vertex = """
 fragment = """
   uniform float antialias;
   varying float v_alpha, v_thickness;
   varying vec2 v_p0, v_p1, v_p;
   void main() {
       float d = 0;
       if( v_p.x < 0 )
           d = length(v_p - v_p0) - v_thickness/2.0 + antialias/2.0;
       else if ( v_p.x > length(v_p1-v_p0) )
           d = length(v_p - v_p1) - v_thickness/2.0 + antialias/2.0;
       else
           d = abs(v_p.y) - v_thickness/2.0 + antialias/2.0;
       if( d < 0)
           gl_FragColor = vec4(0.0, 0.0, 0.0, v_alpha);
       else if (d < antialias) {
           d = exp(-d*d);
           gl_FragColor = vec4(0.0, 0.0, 0.0, d*v_alpha);
       }
+      else {
+          gl_FragColor = vec4(0.0, 0.0, 0.0, 0.0);
+      }
   } """

 window = app.Window(1200, 400, color=(1,1,1,1))

**Comment by rougier** [comment]
Ok, thanks for the explanation. Can you make a PR ?

**Comment by bluebarnacles** [comment]
OK, I created a pull request. I also touched up some of the grammar in the associated paragraph.

**Comment by rougier** [comment]
Thanks, it has been merged.
